version: '3'
services:

  bot-app-csv:
    build:
      context: ./
    restart: always
    command: python3 SlackGlossaryBot/app.py

    env_file:
      - ./bot.env

    volumes:
      - ./config:/opt/SlackGlossaryBot/config
